API-21515-Pingdom Probes
department-of-veterans-affairs/lighthouse-external-monitoring pull request #106
Opened 2022-11-08 18:31 UTC by jkelly-va

2022-11-09 19:09 UTC, mramirez-va requested changes

2022-11-09 19:09 UTC, mramirez-va commented on integration-ids.conf
> +export SLACK_API_ALARMS_DIRECT_DEPOSIT_MANAGEMENT=000000
This will need to be in a separate PR once we have the probe in Pingdom

2022-11-09 19:09 UTC, mramirez-va commented on user-ids.conf
> +export STATUSPAGE_SANDBOX_DIRECT_DEPOSIT_MANAGEMENT=00000000
This will need to be in a separate PR once we have the probe in Pingdom

2022-11-09 19:13 UTC, mramirez-va submitted a review, later dismissed
remove statuspage integration place holders

2022-11-14 19:30 UTC, mramirez-va commented on pingdom-checks/direct-deposit-management.ping
> +  -a group="direct-deposit-management" \
@jkelly-va fyi, I renamed this from `direct-deposit` to match the full API name.

2022-11-14 19:35 UTC, evelez-va approved these changes

2022-11-14 21:51 UTC, mramirez-va approved these changes

2022-11-16 19:09 UTC, jhulbert-va approved these changes
LGTM

2022-11-22 19:28 UTC, merged